import jsPDF from "jspdf";

interface StockAnalysis {
  symbol: string;
  name: string;
  price: number;
  change: number;
  changePercent: number;
  prediction: string;
  confidence: number;
  reasoning: string;
  keyFactors: string[];
}

export const generateStockReport = (analysis: StockAnalysis) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = 20;

  // Header
  pdf.setFontSize(24);
  pdf.setTextColor(103, 104, 224); // Secondary color
  pdf.text("StockLens Analysis Report", margin, yPosition);
  
  yPosition += 10;
  pdf.setFontSize(10);
  pdf.setTextColor(128, 128, 128);
  pdf.text(`Generated on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, margin, yPosition);

  // Stock Info Section
  yPosition += 15;
  pdf.setFontSize(18);
  pdf.setTextColor(0, 0, 0);
  pdf.text(`${analysis.symbol} - ${analysis.name}`, margin, yPosition);

  yPosition += 10;
  pdf.setFontSize(12);
  pdf.text(`Current Price: $${analysis.price}`, margin, yPosition);
  
  yPosition += 7;
  const changeColor = analysis.change >= 0 ? [34, 197, 94] as [number, number, number] : [239, 68, 68] as [number, number, number];
  pdf.setTextColor(changeColor[0], changeColor[1], changeColor[2]);
  pdf.text(`Change: ${analysis.change >= 0 ? '+' : ''}${analysis.change} (${analysis.changePercent}%)`, margin, yPosition);

  // AI Prediction Section
  yPosition += 15;
  pdf.setFontSize(16);
  pdf.setTextColor(0, 0, 0);
  pdf.text("AI Prediction", margin, yPosition);

  yPosition += 10;
  pdf.setFontSize(14);
  const predictionColor = analysis.prediction === "BUY" ? [34, 197, 94] as [number, number, number] : 
                          analysis.prediction === "SELL" ? [239, 68, 68] as [number, number, number] : 
                          [251, 146, 60] as [number, number, number];
  pdf.setTextColor(predictionColor[0], predictionColor[1], predictionColor[2]);
  pdf.text(`Signal: ${analysis.prediction}`, margin, yPosition);

  yPosition += 7;
  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(12);
  pdf.text(`Confidence: ${analysis.confidence}%`, margin, yPosition);

  // Reasoning
  yPosition += 12;
  pdf.setFontSize(14);
  pdf.text("Analysis Reasoning", margin, yPosition);
  
  yPosition += 8;
  pdf.setFontSize(11);
  pdf.setTextColor(64, 64, 64);
  const splitReasoning = pdf.splitTextToSize(analysis.reasoning, pageWidth - 2 * margin);
  pdf.text(splitReasoning, margin, yPosition);
  yPosition += splitReasoning.length * 6;

  // Key Factors
  yPosition += 10;
  pdf.setFontSize(14);
  pdf.setTextColor(0, 0, 0);
  pdf.text("Key Factors", margin, yPosition);

  yPosition += 8;
  pdf.setFontSize(11);
  pdf.setTextColor(64, 64, 64);
  analysis.keyFactors.forEach((factor, index) => {
    const splitFactor = pdf.splitTextToSize(`${index + 1}. ${factor}`, pageWidth - 2 * margin - 5);
    pdf.text(splitFactor, margin, yPosition);
    yPosition += splitFactor.length * 6 + 3;
  });

  // Footer
  yPosition = pdf.internal.pageSize.getHeight() - 20;
  pdf.setFontSize(9);
  pdf.setTextColor(128, 128, 128);
  pdf.text("This report is generated by StockLens AI. Not financial advice.", margin, yPosition);
  pdf.text("Visit stocklens.app for more analysis", margin, yPosition + 5);

  // Save the PDF
  pdf.save(`StockLens_${analysis.symbol}_${new Date().toISOString().split('T')[0]}.pdf`);
};

interface PortfolioReport {
  totalValue: number;
  totalGain: number;
  gainPercent: number;
  holdings: Array<{
    symbol: string;
    shares: number;
    avgPrice: number;
    currentPrice: number;
    value: number;
    gain: number;
  }>;
}

export const generatePortfolioReport = (portfolio: PortfolioReport) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = 20;

  // Header
  pdf.setFontSize(24);
  pdf.setTextColor(103, 104, 224);
  pdf.text("Portfolio Report", margin, yPosition);
  
  yPosition += 10;
  pdf.setFontSize(10);
  pdf.setTextColor(128, 128, 128);
  pdf.text(`Generated on ${new Date().toLocaleDateString()}`, margin, yPosition);

  // Summary Section
  yPosition += 15;
  pdf.setFontSize(16);
  pdf.setTextColor(0, 0, 0);
  pdf.text("Portfolio Summary", margin, yPosition);

  yPosition += 10;
  pdf.setFontSize(12);
  pdf.text(`Total Value: $${portfolio.totalValue.toLocaleString()}`, margin, yPosition);
  
  yPosition += 7;
  const gainColor = portfolio.totalGain >= 0 ? [34, 197, 94] as [number, number, number] : [239, 68, 68] as [number, number, number];
  pdf.setTextColor(gainColor[0], gainColor[1], gainColor[2]);
  pdf.text(`Total Gain: ${portfolio.totalGain >= 0 ? '+' : ''}$${portfolio.totalGain.toFixed(2)} (${portfolio.gainPercent}%)`, margin, yPosition);

  // Holdings Section
  yPosition += 15;
  pdf.setFontSize(16);
  pdf.setTextColor(0, 0, 0);
  pdf.text("Holdings", margin, yPosition);

  yPosition += 10;
  pdf.setFontSize(10);
  
  portfolio.holdings.forEach((holding, index) => {
    if (yPosition > pdf.internal.pageSize.getHeight() - 40) {
      pdf.addPage();
      yPosition = 20;
    }

    pdf.setTextColor(0, 0, 0);
    pdf.setFontSize(12);
    pdf.text(`${holding.symbol}`, margin, yPosition);
    
    pdf.setFontSize(10);
    pdf.setTextColor(64, 64, 64);
    pdf.text(`Shares: ${holding.shares} | Avg Price: $${holding.avgPrice}`, margin, yPosition + 5);
    pdf.text(`Current: $${holding.currentPrice} | Value: $${holding.value.toLocaleString()}`, margin, yPosition + 10);
    
    const holdingGainColor = holding.gain >= 0 ? [34, 197, 94] as [number, number, number] : [239, 68, 68] as [number, number, number];
    pdf.setTextColor(holdingGainColor[0], holdingGainColor[1], holdingGainColor[2]);
    pdf.text(`Gain: ${holding.gain >= 0 ? '+' : ''}$${holding.gain.toFixed(2)}`, margin, yPosition + 15);

    yPosition += 25;
  });

  // Footer
  yPosition = pdf.internal.pageSize.getHeight() - 20;
  pdf.setFontSize(9);
  pdf.setTextColor(128, 128, 128);
  pdf.text("Generated by StockLens - Your AI-powered investment platform", margin, yPosition);

  pdf.save(`Portfolio_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};
